In [2]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [7]:
tokenizer.fit_on_texts(docs)

In [8]:
len(tokenizer.word_index)

17

In [9]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [15]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()

model.add(Embedding(
    input_dim=18,
    output_dim=2,
    input_length=5
))
model.build(input_shape=(None, 5))
model.summary()

e:\Advance ML\Deep_Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile('adam', 'accuracy')

In [26]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
[[[-0.00268223  0.04252682]
  [ 0.01590342  0.02563411]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]]

 [[ 0.01590342  0.02563411]
  [ 0.01590342  0.02563411]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]]

 [[ 0.00010943 -0.04693493]
  [ 0.00010943 -0.04693493]
  [ 0.04769791  0.04268229]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]]

 [[ 0.01344043 -0.04403486]
  [-0.01296511 -0.02496182]
  [ 0.01344043 -0.04403486]
  [ 0.01590342  0.02563411]
  [ 0.01344043 -0.04403486]]

 [[-0.02077545  0.0139914 ]
  [-0.01000864 -0.0341769 ]
  [-0.02724079 -0.04915784]
  [-0.02724061 -0.02114831]
  [-0.02190563  0.01024155]]

 [[-0.04545803 -0.00032841]
  [-0.04545803 -0.00032841]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]
  [-0.02190563  0.01024155]]

 [[-0.0062549  -0.03154536]
  [-0.0062549  -0.03154536]
  [-0.02190563  0.01024155]
  [-0.02190563  0.0102415

In [28]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [46]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

e:\Advance ML\Deep_Learning\venv\Lib\site-packages\numpy\lib\_format_impl.py:838: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  array = pickle.load(fp, **pickle_kwargs)


In [52]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [53]:

X_train.shape

(25000, 50)

In [57]:
model = Sequential()
model.add(Embedding(
    input_dim=10000,
    output_dim=2,
    input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.build(input_shape=(None, 50))

In [58]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.5850 - loss: 0.6569 - val_accuracy: 0.7424 - val_loss: 0.5286
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.8106 - loss: 0.4204 - val_accuracy: 0.8062 - val_loss: 0.4301
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.8636 - loss: 0.3286 - val_accuracy: 0.8004 - val_loss: 0.4356
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.8871 - loss: 0.2814 - val_accuracy: 0.8043 - val_loss: 0.4452
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.9069 - loss: 0.2421 - val_accuracy: 0.7857 - val_loss: 0.6120
